bootstrap verifies packages file exists

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -6,6 +6,14 @@ if [ "$EUID" -eq 0 ]; then
   exit 1
 fi
 
+package_list_path=$XDG_CONFIG_HOME/yadm/packages.txt
+
+if [ ! -f "$package_list_path" ]; then
+  echo "$package_list_path not found"
+  exit 1
+fi
+
+
 sudo pacman -S --noconfirm --needed git base-devel 
 # Install Yay
 if ! command -v yay >/dev/null 2>&1; then
@@ -16,7 +24,7 @@ if ! command -v yay >/dev/null 2>&1; then
 fi
 
 echo "Installing needed packages"
-yay -S --noconfirm --needed --quiet $(< packages.txt) 2>&1 | grep -vi "warning:"
+yay -S --noconfirm --needed --quiet $(< $package_list_path) 2>&1 | grep -vi "warning:"
 
 echo "Installing nvim plugins"
 nvim --headless -c 'Lazy sync' -c 'qa'
