gcloud installation

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -66,6 +66,30 @@ flatpak override --user com.discordapp.Discord \
   --talk-name=org.freedesktop.portal.Desktop \
   --talk-name=org.freedesktop.portal.Documents
 
+install_gcloud() {
+    local tmpdir=$(mktemp -d)
+    trap 'rm -rf "$tmpdir"' EXIT INT TERM
+    curl -fsSLO https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-linux-x86_64.tar.gz \
+      --output-dir "$tmpdir"
+    tar -xf "$tmpdir/google-cloud-cli-linux-x86_64.tar.gz" -C "$HOME"
+    "$HOME/google-cloud-sdk/install.sh" --quiet --path-update false
+    rm -f "$tmpdir/google-cloud-cli-linux-x86_64.tar.gz"
+}
+
+if ! command -v gcloud >/dev/null 2>&1; then
+    echo "gcloud CLI not found. Would you like to install it?"
+    read -r -p "[y/N] " response
+    case "$response" in
+        [yY][eE][sS]|[yY])
+            echo "Installing Google Cloud SDK"
+            (install_gcloud)
+            ;;
+        *)
+            echo "Skipping gcloud CLI installation"
+            ;;
+    esac
+fi
+
 echo "Installing nvim plugins"
 nvim --headless -c 'Lazy sync' -c 'qa'
 
